FROM alpine:3.18.0@sha256:c0669ef34cdc14332c0f1ab0c2c01acb91d96014b172f1a76f3a39e63d1f0bda

ARG ZULU_PKG="zulu11"
ARG UID="1000"
LABEL base=alpine engine=jvm version=java11 timezone=UTC port=8080 dir=/opt/app user=app uid=${UID}

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apk update && wget -P /etc/apk/keys/ https://cdn.azul.com/public_keys/alpine-signing@azul.com-5d5dc44c.rsa.pub && \
    echo "https://repos.azul.com/zulu/alpine" >> /etc/apk/repositories && \
    apk --no-cache add ${ZULU_PKG}-jdk

ENV JAVA_HOME=/usr/lib/jvm/${ZULU_PKG}-ca

RUN apk update && apk add --no-cache tzdata bash gcompat && rm -rf /var/cache/apk/*
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8080

RUN mkdir -p /opt/app && ln -s /opt/app /libs && mkdir -p /opt/db-migrations && ln -s /opt/db-migrations /flyway

WORKDIR /opt/app

RUN addgroup -g 1000 -S appg && \
    addgroup -g 10000 -S app && \
    adduser -u 1000 -G app -S app && \
    adduser -u 10000 -G app -S user && \
    # For backward compatibility
    adduser app appg && \
    chown -R user:app /opt/app /libs /opt/db-migrations /flyway && \
    chmod -R g+rwx /opt/app /libs /opt/db-migrations /flyway
  
USER user


